### ISSUE TITLE
Error: invalid tar file when downloading via NPM

### ISSUE THREAD

**Issue by fracz** [behdad/region-flags#33]
Downloading this package via NPM results in the following error:

```
warn Error on download for github:behdad/region-flags
     Error: invalid tar file
         at Extract.Parse._startEntry (D:\projects\myproject\node_modules\tar\lib\parse.js:149:13)
         at Extract.Parse._process (D:\projects\myproject\node_modules\tar\lib\parse.js:131:12)
         at BlockStream.<anonymous> (D:\projects\myproject\node_modules\tar\lib\parse.js:47:8)
         at emitOne (events.js:96:13)
         at BlockStream.emit (events.js:188:7)
         at BlockStream._emitChunk (D:\projects\myproject\node_modules\block-stream\block-stream.js:145:10)
         at BlockStream.write (D:\projects\myproject\node_modules\block-stream\block-stream.js:45:10)
         at Extract.Parse.write (D:\projects\myproject\node_modules\tar\lib\parse.js:81:23)
         at Gunzip.ondata (_stream_readable.js:555:20)
         at emitOne (events.js:96:13)
         at Gunzip.emit (events.js:188:7)
         at readableAddChunk (_stream_readable.js:176:18)
         at Gunzip.Readable.push (_stream_readable.js:134:10)
         at Gunzip.Transform.push (_stream_transform.js:128:32)
         at Zlib.callback (zlib.js:609:14)

err  Error downloading github:behdad/region-flags.
```

Have you faced it, too? How to fix it?

**Comment by fracz** [comment]
Upgrading from 1.0.1 to 1.1.0 fixed it for me.
